### PR TITLE
Clean up the RDF Entity trait

### PR DESCRIPTION
**Pull request by pfrenssen**
This has been split off from ISAICP-4498. It cleans a dirty trait.

### CODE REVIEW

**Comment by idimopoulos** [comment]
This looks fine. I am waiting for the green to merge.

**Comment by pfrenssen** [comment]
It's some special kind of green.

**Comment by pfrenssen** [comment]
Discovered that this was due to a random failure caused by #1228. Restarting test and created a PR to revert #1228: #1262.

**Comment by pfrenssen** [comment]
Merging this, it was approved by @idimopoulos in his comment above.

**Pull request merged**
