### PR TITLE
Update code to be compatible with latest stable release of Behat

### PR DESCRIPTION
**Pull request by pfrenssen**
We're using Behat Drupal Extension which has pinned a release candidate of Behat 3.1.0. However the latest release of Behat is 3.3.0. This PR explores the possibility of upgrading to the latest stable version.

### CODE REVIEW

**Comment by pfrenssen** [comment]
Great stuff. We are ready if we apply a few minor fixes, we just need to ensure that we declare our callbacks as static methods. Since we were already doing this for the large majority of our callbacks, we can pride ourselves on having top class developer intuition.

We can actually already apply these fixes without actually updating to the latest version of Behat, then we will be ready.

**Comment by pfrenssen** [comment]
I have reverted the composer dependencies. This is ready for review.

**Comment by claudiu-cristea** [comment]
So, here we are only switching to static methods. But I don't see any change to composer dependencies.

**Comment by pfrenssen** [comment]
No, let's wait until the upstream issue is merged first. This update will arrive naturally at some point when we update our composer dependencies.

**Comment by claudiu-cristea** [comment]
I merged the changes. The dependencies to be updates in a future PR.

**Pull request merged**
