### PR TITLE
ISAICP-6787: Optimize Homepage's CSS

### PR DESCRIPTION
**Pull request by theosuja**

### CODE REVIEW

**Comment by theosuja** [comment]
Since I can't see the HP with content, i'd need functional team's help for:
- add "btn btn-secondary" to the button of the "Highlighted event"
- add "btn btn-secondary" to the "Read more" buttons at the bottom of each card in Explore block (make sure it works on all tabs)

cc @pfrenssen

**Comment by theosuja** [comment]
Note: The `!optional` statements on `_global-search-block.scss` must be removed, but this will be handled once this PR is merged with [#2633](https://github.com/ec-europa/joinup-dev/pull/2633) which modifies that same file. There will be merge conflicts in which we must keep #2633 's changes
image

**Review by gingapa — APPROVED** [review]
LGTM, well done!

**Review by pfrenssen — APPROVED** [review]

**Comment by pfrenssen** [comment]
Looking good but we have moved in the meantime to Gitlab. Closing in favor of https://git.fpfis.eu/digit/digit-joinup-dev/-/merge_requests/43

**Pull request closed without merging**
